language: go

go:
- 1.13.x

go_import_path: github.com/hyperledger/fabric

jobs:
  include:
    - stage:  Preliminaries
      script: make basic-checks
    - stage: Unit tests
      script: bash ./scripts/run-unit-tests.sh

